'use strict';

// entries
const _entries = {
  themedark: './src/scss/app-dark.scss',
  themegreen: './src/scss/app-green.scss',
  core: './src/core/hyper.js',
  dsecommerce: './src/dashboard/ecommerce.js',
  dscrm: './src/dashboard/crm.js',
  dsproject: './src/dashboard/projects.js',
  appcalendar: './src/apps/calendar/calendar.js',
  appprojects: './src/apps/project/projects.js',
  appprojectdetail: './src/apps/project/details.js',
  apptasks: './src/apps/task/tasks.js',
  appecommerceproducts: './src/apps/ecommerce/products.js',
  appecommerceshared: './src/apps/ecommerce/shared.js',
  appecommercecustomers: './src/apps/ecommerce/customers.js',
  appecommercesellers: './src/apps/ecommerce/sellers.js',
  appemailinbox: './src/apps/email/inbox.js',
  pagesshared: './src/pages/shared.js',
  pagesprofile: './src/pages/profile/profile.js',
  uishared: './src/ui/shared.js',
  uinotification: './src/ui/notification.js',
  widget: './src/widgets/widget.js',
  formsshared: './src/forms/shared.js',
  formsadvanced: './src/forms/advanced.js',
  formseditor: './src/forms/editors.js',
  formswizard: './src/forms/wizard.js',
  chartjs: './src/charts/chartjs/chartjs.js',
  brite: './src/charts/brite/brite.js',
  apexarea: './src/charts/apex/area.js',
  apexbar: './src/charts/apex/bar.js',
  apexbubble: './src/charts/apex/bubble.js',
  apexcandlestick: './src/charts/apex/candlestick.js',
  apexcolumn: './src/charts/apex/column.js',
  apexheatmap: './src/charts/apex/heatmap.js',
  apexline: './src/charts/apex/line.js',
  apexmixed: './src/charts/apex/mixed.js',
  apexpie: './src/charts/apex/pie.js',
  apexradar: './src/charts/apex/radar.js',
  apexradialbar: './src/charts/apex/radialbar.js',
  apexscatter: './src/charts/apex/scatter.js',
  apexsparklines: './src/charts/apex/sparklines.js',
  sparkline: './src/charts/sparkline/sparkline.js',
  datatable: './src/table/datatable.js',
  googlemap: './src/maps/google/google.js',
  vectormap: './src/maps/vector/vector.js',
};

// pages
const _pages = [
  {
    template: './src/index.html',
    name: 'index',
    filename: 'index.html',
    chunks: ['dsecommerce'],
  },
  {
    template: './src/dashboard/crm.html',
    name: 'dashboard-crm',
    filename: 'dashboard-crm.html',
    chunks: ['dscrm'],
  },
  {
    template: './src/dashboard/projects.html',
    name: 'dashboard-projects',
    filename: 'dashboard-projects.html',
    chunks: ['dsproject'],
  },
  {
    template: './src/apps/calendar/calendar.html',
    name: 'apps-calendar',
    filename: 'apps-calendar.html',
    chunks: ['appcalendar'],
  },
  {
    template: './src/apps/project/list.html',
    name: 'apps-projects-list',
    filename: 'apps-projects-list.html',
    chunks: ['appprojects'],
  },
  {
    template: './src/apps/project/details.html',
    name: 'apps-projects-details',
    filename: 'apps-projects-details.html',
    chunks: ['appprojectdetail'],
  },
  {
    template: './src/apps/task/tasks.html',
    name: 'apps-tasks',
    filename: 'apps-tasks.html',
    chunks: ['apptasks'],
  },
  {
    template: './src/apps/ecommerce/products.html',
    name: 'apps-ecommerce-products',
    filename: 'apps-ecommerce-products.html',
    chunks: ['appecommerceproducts'],
  },
  {
    template: './src/apps/ecommerce/product-details.html',
    name: 'apps-ecommerce-products-details',
    filename: 'apps-ecommerce-products-details.html',
    chunks: ['appecommerceshared'],
  },
  {
    template: './src/apps/ecommerce/orders.html',
    name: 'apps-ecommerce-orders',
    filename: 'apps-ecommerce-orders.html',
    chunks: ['appecommerceshared'],
  },
  {
    template: './src/apps/ecommerce/order-details.html',
    name: 'apps-ecommerce-orders-details',
    filename: 'apps-ecommerce-orders-details.html',
    chunks: ['appecommerceshared'],
  },
  {
    template: './src/apps/ecommerce/customers.html',
    name: 'apps-ecommerce-customers',
    filename: 'apps-ecommerce-customers.html',
    chunks: ['appecommercecustomers'],
  },
  {
    template: './src/apps/ecommerce/shopping-cart.html',
    name: 'apps-ecommerce-shopping-cart',
    filename: 'apps-ecommerce-shopping-cart.html',
    chunks: ['appecommerceshared'],
  },
  {
    template: './src/apps/ecommerce/checkout.html',
    name: 'apps-ecommerce-shopping-cart',
    filename: 'apps-ecommerce-checkout.html',
    chunks: ['appecommerceshared'],
  },
  {
    template: './src/apps/ecommerce/sellers.html',
    name: 'apps-ecommerce-sellers',
    filename: 'apps-ecommerce-sellers.html',
    chunks: ['appecommercesellers'],
  },
  {
    template: './src/apps/email/inbox.html',
    name: 'apps-email-inbox',
    filename: 'apps-email-inbox.html',
    chunks: ['appemailinbox'],
  },
  {
    template: './src/apps/email/detail.html',
    name: 'apps-email-read',
    filename: 'apps-email-read.html',
    chunks: ['appemailinbox'],
  },
  {
    template: './src/pages/starter/starter.html',
    name: 'pages-starter',
    filename: 'pages-starter.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/profile/profile.html',
    name: 'pages-profile',
    filename: 'pages-profile.html',
    chunks: ['pagesprofile'],
  },
  {
    template: './src/pages/invoice/invoice.html',
    name: 'pages-invoice',
    filename: 'pages-invoice.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/faq/faq.html',
    name: 'pages-faq',
    filename: 'pages-faq.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/pricing/pricing.html',
    name: 'pages-pricing',
    filename: 'pages-pricing.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/maintenance/maintenance.html',
    name: 'pages-maintenance',
    filename: 'pages-maintenance.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/auth/login.html',
    name: 'pages-login',
    filename: 'pages-login.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/auth/login2.html',
    name: 'pages-login2',
    filename: 'pages-login-2.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/auth/logout.html',
    name: 'pages-logout',
    filename: 'pages-logout.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/auth/logout2.html',
    name: 'pages-logout2',
    filename: 'pages-logout-2.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/confirm/confirm-mail.html',
    name: 'pages-confirm-mail',
    filename: 'pages-confirm-mail.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/confirm/confirm-mail2.html',
    name: 'pages-confirm-mail-2',
    filename: 'pages-confirm-mail-2.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/error/404.html',
    name: 'pages-404',
    filename: 'pages-404.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/error/404-alt.html',
    name: 'pages-404-alt',
    filename: 'pages-404-alt.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/error/500.html',
    name: 'pages-500',
    filename: 'pages-500.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/lock/lock-screen.html',
    name: 'pages-lock-screen',
    filename: 'pages-lock-screen.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/lock/lock-screen2.html',
    name: 'pages-lock-screen-2',
    filename: 'pages-lock-screen-2.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/password/recoverpw.html',
    name: 'pages-recoverpw',
    filename: 'pages-recoverpw.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/password/recoverpw2.html',
    name: 'pages-recoverpw-2',
    filename: 'pages-recoverpw-2.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/register/register.html',
    name: 'pages-register',
    filename: 'pages-register.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/pages/register/register2.html',
    name: 'pages-register-2',
    filename: 'pages-register-2.html',
    chunks: ['pagesshared'],
  },
  {
    template: './src/ui/buttons.html',
    name: 'ui-buttons',
    filename: 'ui-buttons.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/cards.html',
    name: 'ui-cards',
    filename: 'ui-cards.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/dragula.html',
    name: 'ui-dragula',
    filename: 'ui-dragula.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/general.html',
    name: 'ui-general',
    filename: 'ui-general.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/grid.html',
    name: 'ui-grid',
    filename: 'ui-grid.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/icons.html',
    name: 'ui-icons',
    filename: 'ui-icons.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/modals.html',
    name: 'ui-modals',
    filename: 'ui-modals.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/notifications.html',
    name: 'ui-notifications',
    filename: 'ui-notifications.html',
    chunks: ['uinotification'],
  },
  {
    template: './src/ui/spinners.html',
    name: 'ui-spinners',
    filename: 'ui-spinners.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/tabs.html',
    name: 'ui-tabs',
    filename: 'ui-tabs.html',
    chunks: ['uishared'],
  },
  {
    template: './src/ui/typography.html',
    name: 'ui-typography',
    filename: 'ui-typography.html',
    chunks: ['uishared'],
  },
  {
    template: './src/widgets/widgets.html',
    name: 'widgets',
    filename: 'widgets.html',
    chunks: ['widget'],
  },
  {
    template: './src/forms/basic.html',
    name: 'form-elements',
    filename: 'form-elements.html',
    chunks: ['formsshared'],
  },
  {
    template: './src/forms/advanced.html',
    name: 'form-advanced',
    filename: 'form-advanced.html',
    chunks: ['formsadvanced'],
  },
  {
    template: './src/forms/validation.html',
    name: 'form-validation',
    filename: 'form-validation.html',
    chunks: ['formsshared'],
  },
  {
    template: './src/forms/editors.html',
    name: 'form-editors',
    filename: 'form-editors.html',
    chunks: ['formseditor'],
  },
  {
    template: './src/forms/wizard.html',
    name: 'form-wizard',
    filename: 'form-wizard.html',
    chunks: ['formswizard'],
  },
  {
    template: './src/forms/fileuploads.html',
    name: 'form-fileuploads',
    filename: 'form-fileuploads.html',
    chunks: ['formsshared'],
  },
  {
    template: './src/charts/chartjs/chartjs.html',
    name: 'charts-chartjs',
    filename: 'charts-chartjs.html',
    chunks: ['chartjs'],
  },
  {
    template: './src/charts/brite/brite.html',
    name: 'charts-brite',
    filename: 'charts-brite.html',
    chunks: ['brite'],
  },
  {
    template: './src/charts/apex/area.html',
    name: 'charts-apex-area',
    filename: 'charts-apex-area.html',
    chunks: ['apexarea'],
  },
  {
    template: './src/charts/apex/bar.html',
    name: 'charts-apex-bar',
    filename: 'charts-apex-bar.html',
    chunks: ['apexbar'],
  },
  {
    template: './src/charts/apex/bubble.html',
    name: 'charts-apex-bubble',
    filename: 'charts-apex-bubble.html',
    chunks: ['apexbubble'],
  },
  {
    template: './src/charts/apex/candlestick.html',
    name: 'charts-apex-candlestick',
    filename: 'charts-apex-candlestick.html',
    chunks: ['apexcandlestick'],
  },
  {
    template: './src/charts/apex/column.html',
    name: 'charts-apex-column',
    filename: 'charts-apex-column.html',
    chunks: ['apexcolumn'],
  },
  {
    template: './src/charts/apex/heatmap.html',
    name: 'charts-apex-heatmap',
    filename: 'charts-apex-heatmap.html',
    chunks: ['apexheatmap'],
  },
  {
    template: './src/charts/apex/line.html',
    name: 'charts-apex-line',
    filename: 'charts-apex-line.html',
    chunks: ['apexline'],
  },
  {
    template: './src/charts/apex/mixed.html',
    name: 'charts-apex-mixed',
    filename: 'charts-apex-mixed.html',
    chunks: ['apexmixed'],
  },
  {
    template: './src/charts/apex/pie.html',
    name: 'charts-apex-pie',
    filename: 'charts-apex-pie.html',
    chunks: ['apexpie'],
  },
  {
    template: './src/charts/apex/radar.html',
    name: 'charts-apex-radar',
    filename: 'charts-apex-radar.html',
    chunks: ['apexradar'],
  },
  {
    template: './src/charts/apex/radialbar.html',
    name: 'charts-apex-radialbar',
    filename: 'charts-apex-radialbar.html',
    chunks: ['apexradialbar'],
  },
  {
    template: './src/charts/apex/scatter.html',
    name: 'charts-apex-scatter',
    filename: 'charts-apex-scatter.html',
    chunks: ['apexscatter'],
  },
  {
    template: './src/charts/apex/sparklines.html',
    name: 'charts-apex-sparklines',
    filename: 'charts-apex-sparklines.html',
    chunks: ['apexsparklines'],
  },
  {
    template: './src/charts/sparkline/sparkline.html',
    name: 'charts-sparkline',
    filename: 'charts-sparkline.html',
    chunks: ['sparkline'],
  },
  {
    template: './src/table/basic.html',
    name: 'tables-basic',
    filename: 'tables-basic.html',
    chunks: ['uishared'],
  },
  {
    template: './src/table/datatable.html',
    name: 'tables-datatable',
    filename: 'tables-datatable.html',
    chunks: ['datatable'],
  },
  {
    template: './src/maps/google/google.html',
    name: 'maps-google',
    filename: 'maps-google.html',
    chunks: ['googlemap'],
  },
  {
    template: './src/maps/vector/vector.html',
    name: 'maps-vector',
    filename: 'maps-vector.html',
    chunks: ['vectormap'],
  },
];

// Hyper config class
class HyperConfig {
  static get entries() {
    return _entries;
  }

  static get pages() {
    return _pages;
  }
}

module.exports = HyperConfig;
